#!/bin/sh
# Run on the Linux Docker host after stopping the portal gateway. Never flush other tables.
set -eu
umask 077
port=${2:-23080}
case "$port" in ''|0*|*[!0-9]*) echo 'Invalid gateway port' >&2; exit 2;; esac
[ "${#port}" -le 5 ] && [ "$port" -lt 65535 ] || exit 2
private_networks='0.0.0.0/8, 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.168.0.0/16, 198.18.0.0/15, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 240.0.0.0/4'
render() {
cat <<EOF
table inet dsh_portal_guard {
  set private_v4 {
    type ipv4_addr
    flags interval
    elements = { $private_networks }
  }
  chain input {
    type filter hook input priority -20; policy accept;
    iifname "dshp*" meta nfproto ipv6 drop comment "portal:input:ipv6"
    iifname "dshp*" ct direction reply ct state established,related accept comment "portal:input:reply"
    iifname "dshp*" tcp dport $port accept comment "portal:input:gateway"
    iifname "dshp*" drop comment "portal:input:deny"
  }
  chain forward {
    type filter hook forward priority -20; policy accept;
    iifname "dshp*" meta nfproto ipv6 drop comment "portal:forward:ipv6"
    iifname "dshp*" ip daddr @private_v4 drop comment "portal:forward:private"
    iifname "dshp*" ct state invalid drop comment "portal:forward:invalid"
    iifname "dshp*" accept comment "portal:forward:public"
  }
}
EOF
}
render_fw4_input() {
cat <<EOF
# Generated by dsh-portal v1; only dshp* interfaces.
iifname "dshp*" meta nfproto ipv6 drop comment "portal:fw4:input:ipv6"
iifname "dshp*" ct direction reply ct state established,related accept comment "portal:fw4:input:reply"
iifname "dshp*" tcp dport $port accept comment "portal:fw4:input:gateway"
iifname "dshp*" drop comment "portal:fw4:input:deny"
EOF
}
render_fw4_forward() {
cat <<EOF
# Generated by dsh-portal v1; only dshp* interfaces.
iifname "dshp*" meta nfproto ipv6 drop comment "portal:fw4:forward:ipv6"
iifname "dshp*" ip daddr { $private_networks } drop comment "portal:fw4:forward:private"
iifname "dshp*" ct state invalid drop comment "portal:fw4:forward:invalid"
iifname "dshp*" accept comment "portal:fw4:forward:public"
EOF
}
case ${1:-} in --render) render; exit 0;; --render-fw4-input) render_fw4_input; exit 0;; --render-fw4-forward) render_fw4_forward; exit 0;; install) ;; *) echo 'Usage: install-network-policy.sh install|--render PORT [IMAGE]' >&2; exit 2;; esac
[ "$(uname -s)" = Linux ] && [ "$(id -u)" = 0 ] || { echo 'Linux host root required' >&2; exit 1; }
command -v nft >/dev/null
command -v docker >/dev/null
script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
image=${3:-deepseek-harness-portal:0.1.7}
policy_dir=/run/dsh-portal
mkdir -p "$policy_dir"
[ ! -L "$policy_dir" ] || exit 1
chmod 700 "$policy_dir"
mkdir "$policy_dir/install.lock" || { echo 'Another policy installation is active' >&2; exit 1; }
rules=$(mktemp "$policy_dir/rules.XXXXXX")
cleanup() { rm -f "$rules" "$rules.json" "$rules.fw4" "$rules.fw4.json"; rmdir "$policy_dir/install.lock"; }
trap cleanup EXIT
trap 'exit 1' HUP INT TERM
# An unsuccessful install leaves no marker. Existing nft rules remain until an atomic replacement succeeds.
rm -f "$policy_dir/network-policy.json"
if nft list table inet dsh_portal_guard >/dev/null 2>&1; then echo 'delete table inet dsh_portal_guard' > "$rules"; fi
render >> "$rules"
nft -c -f "$rules"
nft -f "$rules"
if command -v fw4 >/dev/null; then
  for chain in input forward; do
    include_dir=/usr/share/nftables.d/chain-pre/$chain
    include_file=$include_dir/00-dsh-portal.nft
    mkdir -p "$include_dir"
    [ ! -L "$include_dir" ] && [ ! -L "$include_file" ] || exit 1
    if [ -e "$include_file" ]; then
      IFS= read -r first_line < "$include_file"
      [ "$first_line" = '# Generated by dsh-portal v1; only dshp* interfaces.' ] || { echo 'Refusing to replace an unowned fw4 include' >&2; exit 1; }
    fi
    include_tmp=$(mktemp "$include_dir/.dsh-portal.XXXXXX")
    if [ "$chain" = input ]; then render_fw4_input > "$include_tmp"; else render_fw4_forward > "$include_tmp"; fi
    chmod 600 "$include_tmp"
    mv -f "$include_tmp" "$include_file"
  done
  fw4 print > "$rules.fw4"
  grep -F '/usr/share/nftables.d/chain-pre/input/' "$rules.fw4" >/dev/null
  grep -F '/usr/share/nftables.d/chain-pre/forward/' "$rules.fw4" >/dev/null
  nft -c -f "$rules.fw4"
  fw4 reload
  nft -j list table inet fw4 > "$rules.fw4.json"
  docker run --rm --network none --user 0:0 --read-only --entrypoint node \
    --mount "type=bind,src=$script_dir/verify-network-policy.mjs,dst=/verify.mjs,readonly" \
    --mount "type=bind,src=$rules.fw4.json,dst=/policy.json,readonly" "$image" /verify.mjs /policy.json "$port" --fw4
  if ! nft list table inet dsh_portal_guard >/dev/null 2>&1; then render > "$rules"; nft -f "$rules"; fi
fi
nft -j list table inet dsh_portal_guard > "$rules.json"
docker run --rm --network none --user 0:0 --read-only --entrypoint node \
  --mount "type=bind,src=$script_dir/verify-network-policy.mjs,dst=/verify.mjs,readonly" \
  --mount "type=bind,src=$rules.json,dst=/policy.json,readonly" "$image" /verify.mjs /policy.json "$port"
sh "$script_dir/verify-network-policy.sh" "$image" "$port"
marker=$(mktemp "$policy_dir/marker.XXXXXX")
printf '{"version":1,"interfacePrefix":"dshp","gatewayPort":%s,"denyPrivate":true}\n' "$port" > "$marker"
chmod 600 "$marker"
mv -f "$marker" "$policy_dir/network-policy.json"
echo 'Network policy installed and verified; gateway may now start.'
